apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 33
    ndkVersion "21.4.7075529"

    namespace "com.emu.gba"

    defaultConfig {
        applicationId "com.emu.gba"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            ndkBuild {
                abiFilters "armeabi-v7a", "arm64-v8a"
            }
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "../jni/Android.mk"
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            kotlin.srcDirs = ['src/main/kotlin']
            res.srcDirs = ['src/main/res']
            
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "androidx.documentfile:documentfile:1.0.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
}
